CREATE TABLE user_account (
    id VARCHAR(36) PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    role VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE conversation (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    title VARCHAR(120) NOT NULL,
    message_count INT NOT NULL DEFAULT 0,
    last_message_preview VARCHAR(240),
    last_message_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_conversation_user FOREIGN KEY (user_id) REFERENCES user_account(id)
);
CREATE INDEX idx_conversation_user_active_updated
    ON conversation(user_id, deleted_at, updated_at);

CREATE TABLE chat_message (
    id VARCHAR(36) PRIMARY KEY,
    conversation_id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    role VARCHAR(20) NOT NULL,
    agent_key VARCHAR(64),
    content TEXT NOT NULL,
    cards_json TEXT,
    intents VARCHAR(255),
    trace_id VARCHAR(64),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id) REFERENCES conversation(id),
    CONSTRAINT fk_message_user FOREIGN KEY (user_id) REFERENCES user_account(id)
);
CREATE INDEX idx_message_conversation_created
    ON chat_message(conversation_id, created_at);

CREATE TABLE travel_approval (
    id VARCHAR(36) PRIMARY KEY,
    approval_no VARCHAR(32) NOT NULL UNIQUE,
    request_id VARCHAR(80) NOT NULL UNIQUE,
    user_id VARCHAR(36) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    destination VARCHAR(80) NOT NULL,
    travel_date VARCHAR(20) NOT NULL,
    budget DECIMAL(12, 2),
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_approval_user FOREIGN KEY (user_id) REFERENCES user_account(id)
);
CREATE INDEX idx_approval_user_tenant_created
    ON travel_approval(user_id, tenant_id, created_at);

CREATE TABLE policy_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    title VARCHAR(160) NOT NULL,
    content TEXT NOT NULL,
    keywords VARCHAR(500) NOT NULL,
    source VARCHAR(160) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX idx_policy_tenant_enabled ON policy_document(tenant_id, enabled);
